import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import PageBorder from "@/components/PageBorder";
import { AuthProvider } from "@/context/auth";

export const metadata: Metadata = {
  title: "Fail Safe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <AuthProvider>
          <PageBorder>{children}</PageBorder>
        </AuthProvider>
      </body>
    </html>
  );
}
