import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'; 
import PageBorder from "../components/PageBorder";

export const metadata: Metadata = {
  title: "Fail Safe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <PageBorder>
        {children}
        </PageBorder>
      </body>
    </html>
  );
}
